/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAirportsRouteImport } from './routes/admin.airports'
import { Route as AdminAirportsCodeRouteImport } from './routes/admin.airports.$code'
import { Route as AuthenticatedDashboardAirportsRouteImport } from './routes/_authenticated/dashboard.airports'
import { Route as AuthenticatedAirportCodeFlightsRouteImport } from './routes/_authenticated/airport.$code.flights'
import { Route as AuthenticatedAirportCodeFlightStatusRouteImport } from './routes/_authenticated/airport.$code.flight-status'
import { Route as AuthenticatedAirportCodeDashboardRouteImport } from './routes/_authenticated/airport.$code.dashboard'
import { Route as AuthenticatedAirportCodeBoardingPassRouteImport } from './routes/_authenticated/airport.$code.boarding-pass'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAirportsRoute = AdminAirportsRouteImport.update({
  id: '/airports',
  path: '/airports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAirportsCodeRoute = AdminAirportsCodeRouteImport.update({
  id: '/$code',
  path: '/$code',
  getParentRoute: () => AdminAirportsRoute,
} as any)
const AuthenticatedDashboardAirportsRoute =
  AuthenticatedDashboardAirportsRouteImport.update({
    id: '/dashboard/airports',
    path: '/dashboard/airports',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAirportCodeFlightsRoute =
  AuthenticatedAirportCodeFlightsRouteImport.update({
    id: '/airport/$code/flights',
    path: '/airport/$code/flights',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAirportCodeFlightStatusRoute =
  AuthenticatedAirportCodeFlightStatusRouteImport.update({
    id: '/airport/$code/flight-status',
    path: '/airport/$code/flight-status',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAirportCodeDashboardRoute =
  AuthenticatedAirportCodeDashboardRouteImport.update({
    id: '/airport/$code/dashboard',
    path: '/airport/$code/dashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAirportCodeBoardingPassRoute =
  AuthenticatedAirportCodeBoardingPassRouteImport.update({
    id: '/airport/$code/boarding-pass',
    path: '/airport/$code/boarding-pass',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/admin/airports': typeof AdminAirportsRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/dashboard/airports': typeof AuthenticatedDashboardAirportsRoute
  '/admin/airports/$code': typeof AdminAirportsCodeRoute
  '/airport/$code/boarding-pass': typeof AuthenticatedAirportCodeBoardingPassRoute
  '/airport/$code/dashboard': typeof AuthenticatedAirportCodeDashboardRoute
  '/airport/$code/flight-status': typeof AuthenticatedAirportCodeFlightStatusRoute
  '/airport/$code/flights': typeof AuthenticatedAirportCodeFlightsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin/airports': typeof AdminAirportsRouteWithChildren
  '/admin': typeof AdminIndexRoute
  '/dashboard/airports': typeof AuthenticatedDashboardAirportsRoute
  '/admin/airports/$code': typeof AdminAirportsCodeRoute
  '/airport/$code/boarding-pass': typeof AuthenticatedAirportCodeBoardingPassRoute
  '/airport/$code/dashboard': typeof AuthenticatedAirportCodeDashboardRoute
  '/airport/$code/flight-status': typeof AuthenticatedAirportCodeFlightStatusRoute
  '/airport/$code/flights': typeof AuthenticatedAirportCodeFlightsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/admin/airports': typeof AdminAirportsRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/_authenticated/dashboard/airports': typeof AuthenticatedDashboardAirportsRoute
  '/admin/airports/$code': typeof AdminAirportsCodeRoute
  '/_authenticated/airport/$code/boarding-pass': typeof AuthenticatedAirportCodeBoardingPassRoute
  '/_authenticated/airport/$code/dashboard': typeof AuthenticatedAirportCodeDashboardRoute
  '/_authenticated/airport/$code/flight-status': typeof AuthenticatedAirportCodeFlightStatusRoute
  '/_authenticated/airport/$code/flights': typeof AuthenticatedAirportCodeFlightsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/admin/airports'
    | '/admin/'
    | '/dashboard/airports'
    | '/admin/airports/$code'
    | '/airport/$code/boarding-pass'
    | '/airport/$code/dashboard'
    | '/airport/$code/flight-status'
    | '/airport/$code/flights'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin/airports'
    | '/admin'
    | '/dashboard/airports'
    | '/admin/airports/$code'
    | '/airport/$code/boarding-pass'
    | '/airport/$code/dashboard'
    | '/airport/$code/flight-status'
    | '/airport/$code/flights'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin'
    | '/auth'
    | '/admin/airports'
    | '/admin/'
    | '/_authenticated/dashboard/airports'
    | '/admin/airports/$code'
    | '/_authenticated/airport/$code/boarding-pass'
    | '/_authenticated/airport/$code/dashboard'
    | '/_authenticated/airport/$code/flight-status'
    | '/_authenticated/airport/$code/flights'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/airports': {
      id: '/admin/airports'
      path: '/airports'
      fullPath: '/admin/airports'
      preLoaderRoute: typeof AdminAirportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/airports/$code': {
      id: '/admin/airports/$code'
      path: '/$code'
      fullPath: '/admin/airports/$code'
      preLoaderRoute: typeof AdminAirportsCodeRouteImport
      parentRoute: typeof AdminAirportsRoute
    }
    '/_authenticated/dashboard/airports': {
      id: '/_authenticated/dashboard/airports'
      path: '/dashboard/airports'
      fullPath: '/dashboard/airports'
      preLoaderRoute: typeof AuthenticatedDashboardAirportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/airport/$code/flights': {
      id: '/_authenticated/airport/$code/flights'
      path: '/airport/$code/flights'
      fullPath: '/airport/$code/flights'
      preLoaderRoute: typeof AuthenticatedAirportCodeFlightsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/airport/$code/flight-status': {
      id: '/_authenticated/airport/$code/flight-status'
      path: '/airport/$code/flight-status'
      fullPath: '/airport/$code/flight-status'
      preLoaderRoute: typeof AuthenticatedAirportCodeFlightStatusRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/airport/$code/dashboard': {
      id: '/_authenticated/airport/$code/dashboard'
      path: '/airport/$code/dashboard'
      fullPath: '/airport/$code/dashboard'
      preLoaderRoute: typeof AuthenticatedAirportCodeDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/airport/$code/boarding-pass': {
      id: '/_authenticated/airport/$code/boarding-pass'
      path: '/airport/$code/boarding-pass'
      fullPath: '/airport/$code/boarding-pass'
      preLoaderRoute: typeof AuthenticatedAirportCodeBoardingPassRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardAirportsRoute: typeof AuthenticatedDashboardAirportsRoute
  AuthenticatedAirportCodeBoardingPassRoute: typeof AuthenticatedAirportCodeBoardingPassRoute
  AuthenticatedAirportCodeDashboardRoute: typeof AuthenticatedAirportCodeDashboardRoute
  AuthenticatedAirportCodeFlightStatusRoute: typeof AuthenticatedAirportCodeFlightStatusRoute
  AuthenticatedAirportCodeFlightsRoute: typeof AuthenticatedAirportCodeFlightsRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardAirportsRoute: AuthenticatedDashboardAirportsRoute,
  AuthenticatedAirportCodeBoardingPassRoute:
    AuthenticatedAirportCodeBoardingPassRoute,
  AuthenticatedAirportCodeDashboardRoute:
    AuthenticatedAirportCodeDashboardRoute,
  AuthenticatedAirportCodeFlightStatusRoute:
    AuthenticatedAirportCodeFlightStatusRoute,
  AuthenticatedAirportCodeFlightsRoute: AuthenticatedAirportCodeFlightsRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface AdminAirportsRouteChildren {
  AdminAirportsCodeRoute: typeof AdminAirportsCodeRoute
}

const AdminAirportsRouteChildren: AdminAirportsRouteChildren = {
  AdminAirportsCodeRoute: AdminAirportsCodeRoute,
}

const AdminAirportsRouteWithChildren = AdminAirportsRoute._addFileChildren(
  AdminAirportsRouteChildren,
)

interface AdminRouteChildren {
  AdminAirportsRoute: typeof AdminAirportsRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAirportsRoute: AdminAirportsRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
