/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardAirportsRouteImport } from './routes/_authenticated/dashboard.airports'
import { Route as AuthenticatedAdminPassengersRouteImport } from './routes/_authenticated/admin.passengers'
import { Route as AuthenticatedAdminDashboardRouteImport } from './routes/_authenticated/admin.dashboard'
import { Route as AuthenticatedAdminAirportsRouteImport } from './routes/_authenticated/admin.airports'
import { Route as AuthenticatedAirportCodeFlightsRouteImport } from './routes/_authenticated/airport.$code.flights'
import { Route as AuthenticatedAirportCodeFlightStatusRouteImport } from './routes/_authenticated/airport.$code.flight-status'
import { Route as AuthenticatedAirportCodeDashboardRouteImport } from './routes/_authenticated/airport.$code.dashboard'
import { Route as AuthenticatedAirportCodeBoardingPassRouteImport } from './routes/_authenticated/airport.$code.boarding-pass'
import { Route as AuthenticatedAdminAirportsCodeRouteImport } from './routes/_authenticated/admin.airports.$code'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardAirportsRoute =
  AuthenticatedDashboardAirportsRouteImport.update({
    id: '/dashboard/airports',
    path: '/dashboard/airports',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminPassengersRoute =
  AuthenticatedAdminPassengersRouteImport.update({
    id: '/admin/passengers',
    path: '/admin/passengers',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminDashboardRoute =
  AuthenticatedAdminDashboardRouteImport.update({
    id: '/admin/dashboard',
    path: '/admin/dashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminAirportsRoute =
  AuthenticatedAdminAirportsRouteImport.update({
    id: '/admin/airports',
    path: '/admin/airports',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAirportCodeFlightsRoute =
  AuthenticatedAirportCodeFlightsRouteImport.update({
    id: '/airport/$code/flights',
    path: '/airport/$code/flights',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAirportCodeFlightStatusRoute =
  AuthenticatedAirportCodeFlightStatusRouteImport.update({
    id: '/airport/$code/flight-status',
    path: '/airport/$code/flight-status',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAirportCodeDashboardRoute =
  AuthenticatedAirportCodeDashboardRouteImport.update({
    id: '/airport/$code/dashboard',
    path: '/airport/$code/dashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAirportCodeBoardingPassRoute =
  AuthenticatedAirportCodeBoardingPassRouteImport.update({
    id: '/airport/$code/boarding-pass',
    path: '/airport/$code/boarding-pass',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminAirportsCodeRoute =
  AuthenticatedAdminAirportsCodeRouteImport.update({
    id: '/$code',
    path: '/$code',
    getParentRoute: () => AuthenticatedAdminAirportsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin/airports': typeof AuthenticatedAdminAirportsRouteWithChildren
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/passengers': typeof AuthenticatedAdminPassengersRoute
  '/dashboard/airports': typeof AuthenticatedDashboardAirportsRoute
  '/admin/airports/$code': typeof AuthenticatedAdminAirportsCodeRoute
  '/airport/$code/boarding-pass': typeof AuthenticatedAirportCodeBoardingPassRoute
  '/airport/$code/dashboard': typeof AuthenticatedAirportCodeDashboardRoute
  '/airport/$code/flight-status': typeof AuthenticatedAirportCodeFlightStatusRoute
  '/airport/$code/flights': typeof AuthenticatedAirportCodeFlightsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin/airports': typeof AuthenticatedAdminAirportsRouteWithChildren
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/passengers': typeof AuthenticatedAdminPassengersRoute
  '/dashboard/airports': typeof AuthenticatedDashboardAirportsRoute
  '/admin/airports/$code': typeof AuthenticatedAdminAirportsCodeRoute
  '/airport/$code/boarding-pass': typeof AuthenticatedAirportCodeBoardingPassRoute
  '/airport/$code/dashboard': typeof AuthenticatedAirportCodeDashboardRoute
  '/airport/$code/flight-status': typeof AuthenticatedAirportCodeFlightStatusRoute
  '/airport/$code/flights': typeof AuthenticatedAirportCodeFlightsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin/airports': typeof AuthenticatedAdminAirportsRouteWithChildren
  '/_authenticated/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/_authenticated/admin/passengers': typeof AuthenticatedAdminPassengersRoute
  '/_authenticated/dashboard/airports': typeof AuthenticatedDashboardAirportsRoute
  '/_authenticated/admin/airports/$code': typeof AuthenticatedAdminAirportsCodeRoute
  '/_authenticated/airport/$code/boarding-pass': typeof AuthenticatedAirportCodeBoardingPassRoute
  '/_authenticated/airport/$code/dashboard': typeof AuthenticatedAirportCodeDashboardRoute
  '/_authenticated/airport/$code/flight-status': typeof AuthenticatedAirportCodeFlightStatusRoute
  '/_authenticated/airport/$code/flights': typeof AuthenticatedAirportCodeFlightsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin/airports'
    | '/admin/dashboard'
    | '/admin/passengers'
    | '/dashboard/airports'
    | '/admin/airports/$code'
    | '/airport/$code/boarding-pass'
    | '/airport/$code/dashboard'
    | '/airport/$code/flight-status'
    | '/airport/$code/flights'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin/airports'
    | '/admin/dashboard'
    | '/admin/passengers'
    | '/dashboard/airports'
    | '/admin/airports/$code'
    | '/airport/$code/boarding-pass'
    | '/airport/$code/dashboard'
    | '/airport/$code/flight-status'
    | '/airport/$code/flights'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin/airports'
    | '/_authenticated/admin/dashboard'
    | '/_authenticated/admin/passengers'
    | '/_authenticated/dashboard/airports'
    | '/_authenticated/admin/airports/$code'
    | '/_authenticated/airport/$code/boarding-pass'
    | '/_authenticated/airport/$code/dashboard'
    | '/_authenticated/airport/$code/flight-status'
    | '/_authenticated/airport/$code/flights'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard/airports': {
      id: '/_authenticated/dashboard/airports'
      path: '/dashboard/airports'
      fullPath: '/dashboard/airports'
      preLoaderRoute: typeof AuthenticatedDashboardAirportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/passengers': {
      id: '/_authenticated/admin/passengers'
      path: '/admin/passengers'
      fullPath: '/admin/passengers'
      preLoaderRoute: typeof AuthenticatedAdminPassengersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/dashboard': {
      id: '/_authenticated/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AuthenticatedAdminDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/airports': {
      id: '/_authenticated/admin/airports'
      path: '/admin/airports'
      fullPath: '/admin/airports'
      preLoaderRoute: typeof AuthenticatedAdminAirportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/airport/$code/flights': {
      id: '/_authenticated/airport/$code/flights'
      path: '/airport/$code/flights'
      fullPath: '/airport/$code/flights'
      preLoaderRoute: typeof AuthenticatedAirportCodeFlightsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/airport/$code/flight-status': {
      id: '/_authenticated/airport/$code/flight-status'
      path: '/airport/$code/flight-status'
      fullPath: '/airport/$code/flight-status'
      preLoaderRoute: typeof AuthenticatedAirportCodeFlightStatusRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/airport/$code/dashboard': {
      id: '/_authenticated/airport/$code/dashboard'
      path: '/airport/$code/dashboard'
      fullPath: '/airport/$code/dashboard'
      preLoaderRoute: typeof AuthenticatedAirportCodeDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/airport/$code/boarding-pass': {
      id: '/_authenticated/airport/$code/boarding-pass'
      path: '/airport/$code/boarding-pass'
      fullPath: '/airport/$code/boarding-pass'
      preLoaderRoute: typeof AuthenticatedAirportCodeBoardingPassRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/airports/$code': {
      id: '/_authenticated/admin/airports/$code'
      path: '/$code'
      fullPath: '/admin/airports/$code'
      preLoaderRoute: typeof AuthenticatedAdminAirportsCodeRouteImport
      parentRoute: typeof AuthenticatedAdminAirportsRoute
    }
  }
}

interface AuthenticatedAdminAirportsRouteChildren {
  AuthenticatedAdminAirportsCodeRoute: typeof AuthenticatedAdminAirportsCodeRoute
}

const AuthenticatedAdminAirportsRouteChildren: AuthenticatedAdminAirportsRouteChildren =
  {
    AuthenticatedAdminAirportsCodeRoute: AuthenticatedAdminAirportsCodeRoute,
  }

const AuthenticatedAdminAirportsRouteWithChildren =
  AuthenticatedAdminAirportsRoute._addFileChildren(
    AuthenticatedAdminAirportsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAdminAirportsRoute: typeof AuthenticatedAdminAirportsRouteWithChildren
  AuthenticatedAdminDashboardRoute: typeof AuthenticatedAdminDashboardRoute
  AuthenticatedAdminPassengersRoute: typeof AuthenticatedAdminPassengersRoute
  AuthenticatedDashboardAirportsRoute: typeof AuthenticatedDashboardAirportsRoute
  AuthenticatedAirportCodeBoardingPassRoute: typeof AuthenticatedAirportCodeBoardingPassRoute
  AuthenticatedAirportCodeDashboardRoute: typeof AuthenticatedAirportCodeDashboardRoute
  AuthenticatedAirportCodeFlightStatusRoute: typeof AuthenticatedAirportCodeFlightStatusRoute
  AuthenticatedAirportCodeFlightsRoute: typeof AuthenticatedAirportCodeFlightsRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminAirportsRoute: AuthenticatedAdminAirportsRouteWithChildren,
  AuthenticatedAdminDashboardRoute: AuthenticatedAdminDashboardRoute,
  AuthenticatedAdminPassengersRoute: AuthenticatedAdminPassengersRoute,
  AuthenticatedDashboardAirportsRoute: AuthenticatedDashboardAirportsRoute,
  AuthenticatedAirportCodeBoardingPassRoute:
    AuthenticatedAirportCodeBoardingPassRoute,
  AuthenticatedAirportCodeDashboardRoute:
    AuthenticatedAirportCodeDashboardRoute,
  AuthenticatedAirportCodeFlightStatusRoute:
    AuthenticatedAirportCodeFlightStatusRoute,
  AuthenticatedAirportCodeFlightsRoute: AuthenticatedAirportCodeFlightsRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
