/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardAirportsRouteImport } from './routes/_authenticated/dashboard.airports'
import { Route as AuthenticatedAdminAirportsRouteImport } from './routes/_authenticated/admin.airports'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardAirportsRoute =
  AuthenticatedDashboardAirportsRouteImport.update({
    id: '/dashboard/airports',
    path: '/dashboard/airports',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminAirportsRoute =
  AuthenticatedAdminAirportsRouteImport.update({
    id: '/admin/airports',
    path: '/admin/airports',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin/airports': typeof AuthenticatedAdminAirportsRoute
  '/dashboard/airports': typeof AuthenticatedDashboardAirportsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin/airports': typeof AuthenticatedAdminAirportsRoute
  '/dashboard/airports': typeof AuthenticatedDashboardAirportsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin/airports': typeof AuthenticatedAdminAirportsRoute
  '/_authenticated/dashboard/airports': typeof AuthenticatedDashboardAirportsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/admin/airports' | '/dashboard/airports'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/admin/airports' | '/dashboard/airports'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin/airports'
    | '/_authenticated/dashboard/airports'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard/airports': {
      id: '/_authenticated/dashboard/airports'
      path: '/dashboard/airports'
      fullPath: '/dashboard/airports'
      preLoaderRoute: typeof AuthenticatedDashboardAirportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/airports': {
      id: '/_authenticated/admin/airports'
      path: '/admin/airports'
      fullPath: '/admin/airports'
      preLoaderRoute: typeof AuthenticatedAdminAirportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAdminAirportsRoute: typeof AuthenticatedAdminAirportsRoute
  AuthenticatedDashboardAirportsRoute: typeof AuthenticatedDashboardAirportsRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminAirportsRoute: AuthenticatedAdminAirportsRoute,
  AuthenticatedDashboardAirportsRoute: AuthenticatedDashboardAirportsRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
